In [1]:
import numpy as np
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [4]:
#1. How many negative numbers are there?
negative = a < 0 
len(a[negative])

4

In [5]:
#2. How many positive numbers are there?
positive = a > 0
len(a[positive])

5

In [309]:
##3. How many even positive numbers are there?
step_1 = a % 2
step_2 = step_1 == 0
step_3 = step_2
step_3
even_positive_numbers = step_3 >= 0
a[even_positive_numbers]

# should be 6

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [281]:
#4. If you were to add 3 to each data point, how many positive numbers would there be?
plus_three = a + 3
plus_three
positive_numbers = plus_three >= 0
len(a[positive_numbers])

10

In [52]:
#5. If you squared each number, what would the new mean and standard deviation be?
numbers_squared = a ** 2
np.mean(numbers_squared), np.std(numbers_squared)

(74.0, 144.0243035046516)

In [94]:
#6. A common statistical operation on a dataset is centering. This means to adjust the data such that the center of the data is at 0. This is done by subtracting the mean from each data point. Center the data set.
a - np.mean(a)

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [95]:
#7. Calculate the z-score for each data point. Recall that the z-score is given by: Z = x - mean / std 
a - np.mean(a) / np.std(a)

array([ 3.6278958,  9.6278958, 11.6278958, 22.6278958, -2.3721042,
       -1.3721042, -0.3721042, -0.3721042, -0.3721042, -6.3721042,
        2.6278958, -7.3721042])

In [ ]:
#8. Copy the setup and exercise directions from More Numpy Practice into your 4.7_numpy_exercises.py and add your solutions.

In [315]:
import numpy as np
# Life w/o numpy to life with numpy

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Use python's built in functionality/operators to determine the following:

In [318]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a = np.sum(a)
sum_of_a

55

In [98]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = np.min(a)
min_of_a

1

In [99]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = np.max(a)
max_of_a

10

In [100]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = np.mean(a)
mean_of_a

5.5

In [101]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
product_of_a = np.prod(a)
product_of_a

3628800

In [102]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_a = np.square(a)
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [313]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_a = a % 2 == 1
a[odds_in_a]

array([1, 3, 5, 7, 9])

In [314]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = a % 2 == 0
a[evens_in_a]

array([ 2,  4,  6,  8, 10])

In [320]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

b = np.array([
    [3, 4, 5],
    [6, 7, 8]
])

In [176]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)
sum_of_b = np.array([
    [3, 4, 5],
    [6, 7, 8]
])
np.sum(sum_of_b)

33

In [178]:
# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1]) 
min_of_b = np.array([min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1]) ])
min_of_b

array([3])

In [179]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
max_of_b = np.array([max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])])
max_of_b

array([8])

In [180]:
# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len([b[0]]) + len(b[1]))
mean_of_b = np.array([(sum(b[0]) + sum(b[1])) / (len([b[0]]) + len(b[1]))])
mean_of_b

array([8.25])

In [182]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
product_of_b = np.array([[
    [3, 4, 5],
    [6, 7, 8]
]])        
np.prod(product_of_b)

20160

In [183]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
squares_of_b = np.array([[
    [3, 4, 5],
    [6, 7, 8]
]])
np.square(squares_of_b)

array([[[ 9, 16, 25],
        [36, 49, 64]]])

In [322]:
## Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
odds_of_b = np.array([[
    [3, 4, 5],
    [6, 7, 8]
]])
odds_of_b

array([[[3, 4, 5],
        [6, 7, 8]]])

In [ ]:
## Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
evens_of_b = np.array([[
    [3, 4, 5],
    [6, 7, 8]
]])   


In [186]:
# Exercise 9 - print out the shape of the array b.
np.shape(b)

(2, 3)

In [187]:
# Exercise 10 - transpose the array b.
np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

In [201]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
np.reshape(b, (1, 6))

array([[3, 4, 5, 6, 7, 8]])

In [202]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
np.reshape(b, (6, 1))

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [204]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.

In [206]:
# Exercise 1 - Find the min, max, sum, and product of c.
c = np.array([[
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]])
np.min(c), np.max(c), np.sum(c), np.prod(c)

(1, 9, 45, 362880)

In [207]:
# Exercise 2 - Determine the standard deviation of c.
np.std(c)

2.581988897471611

In [208]:
# Exercise 3 - Determine the variance of c.
np.var(c)

6.666666666666667

In [209]:
# Exercise 4 - Print out the shape of the array c
np.shape(c)

(1, 3, 3)

In [229]:
# Exercise 5 - Transpose c and print out transposed result.
print(np.transpose(c))

[[[1]
  [4]
  [7]]

 [[2]
  [5]
  [8]]

 [[3]
  [6]
  [9]]]


In [246]:
# Exercise 6 - Multiply c by the c-Transposed and print the result.
print(c * np.transpose(c))

[[[ 1  2  3]
  [16 20 24]
  [49 56 63]]

 [[ 2  4  6]
  [20 25 30]
  [56 64 72]]

 [[ 3  6  9]
  [24 30 36]
  [63 72 81]]]


In [244]:
## Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261
np.sum(c * np.transpose(c))

837

In [245]:
## Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.
np.prod(c*np.transpose(c))

-2842928051103203328

In [255]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
d = np.array([[
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]])

In [249]:
# Exercise 1 - Find the sine of all the numbers in d
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [250]:
# Exercise 2 - Find the cosine of all the numbers in d
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [251]:
# Exercise 3 - Find the tangent of all the numbers in d
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [258]:
# Exercise 4 - Find all the negative numbers in d
neg_nums = d[d<0]
neg_nums

array([-90, -30, -45, -45])

In [259]:
# Exercise 5 - Find all the positive numbers in d
pos_nums = d[d>0]
pos_nums

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [260]:
# Exercise 6 - Return an array of only the unique numbers in d.
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [261]:
# Exercise 7 - Determine how many unique numbers there are in d.
len(np.unique(d))

11

In [262]:
# Exercise 8 - Print out the shape of d.
print(np.shape(d))

(1, 3, 6)


In [264]:
# Exercise 9 - Transpose and then print out the shape of d.
np.transpose(d)
print(np.shape(np.transpose(d)))

(6, 3, 1)


In [266]:
# Exercise 10 - Reshape d into an array of 9 x 2
np.reshape(d, (9, 2))

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])